src/background.ts
src/content.ts
src/lib/censys.ts
src/lib/command.ts
src/lib/domainbigdata.ts
src/lib/findsubdomains.ts
src/lib/hybridanalysis.ts
src/lib/publicwww.ts
src/lib/pulsedive.ts
src/lib/securitytrails.ts
src/lib/selector.ts
src/lib/shodan.ts
src/lib/urlscan.ts
src/lib/virustotal.ts
src/options.ts
src/spec/censys.spec.ts
src/spec/command.spec.ts
src/spec/domainbigdata.spec.ts
src/spec/findsubdomains.spec.ts
src/spec/hybridanalysis.spec.ts
src/spec/publicwww.spec.ts
src/spec/pulsedive.spec.ts
src/spec/securitytails.spec.ts
src/spec/selector.spec.ts
src/spec/shodan.spec.ts
src/spec/urlscan.spec.ts
src/spec/virustotal.spec.ts
tslint.json

To be honest, I cannot remember why I was using single quotes.

Switch to use double quotes

---

src/background.ts

It's useless because it doesn't make any good effects.

Remove unnecessary context menu removal

---

src/spec/urlscan.spec.ts

Remove unnecessary test cases

---

README.md
dist/manifest.json

Merged 6 PRs:
- #17 
- #18 
- #19 
- #20 
- #21 
- #22

Bum the version up!

---

dist/manifest.json
dist/options.html
package-lock.json
package.json
src/background.ts
src/lib/command.ts
src/lib/scanner/index.ts
src/lib/scanner/scanner.ts
src/lib/scanner/urlscan.ts
src/lib/scanner/virustotal.ts
src/lib/selector.ts
src/lib/urlscan.ts
src/lib/virustotal.ts
src/options.ts
src/spec/command.spec.ts
src/spec/scanner/selector.spec.ts
src/spec/selector.spec.ts
src/spec/urlscan.spec.ts

Add VT scan feature

---

src/lib/searcher/index.ts
src/lib/searcher/virustotal.ts
src/lib/searcher/xforce-exchange.ts
src/lib/selector.ts
src/spec/searcher/xforce-exchange.spec.ts
src/spec/selector.spec.ts

Implemented the feature which is mentioned in #31

Add X-Force-Exchange support

---

src/background.ts
src/content.ts
tslint.json

Fix(?) an issue which is reported in #36.
(Just adding an error assertion in `chrome.contextMenus.create`, so it's not fix the root issue.)

Add an error handler for chrome.contextMenus.create

---

src/background.ts

Fix an issue which is reported in #37

Fix an issue in storage.get

---

dist/manifest.json
package-lock.json
package.json
src/content.ts

Throttled onSelectionChange event

Add throttle-debounce

---

src/content.ts

Change throttle delay

---

src/lib/command.ts
src/lib/searcher/index.ts
src/lib/searcher/searcher.ts
src/lib/searcher/searchers.ts
src/lib/searcher/threatcrowd.ts
src/lib/searcher/viewdns.ts
src/lib/selector.ts
src/spec/searcher/threatcrowd.spec.ts
src/spec/searcher/viewdns.spec.ts
src/spec/selector.spec.ts

Implemented #53.
I cannot find the way DomainBigdata deals with encoding domain. So I don't implement it.

Add email lookup feature

---

src/lib/searcher/cymon.ts
src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/spec/searcher/cymon.spec.ts
src/spec/selector.spec.ts

Add Cymon support

---

src/content.ts

I think 250 reduces bustage issues(e.g. context menu duplications)

Change 100 to 250

---

dist/manifest.json
package-lock.json
package.json

chore: v0.18.1

---

src/lib/command.ts
src/lib/searcher/index.ts
src/lib/searcher/searcher.ts
src/lib/searcher/searchers.ts
src/lib/searcher/vulmon.ts
src/lib/selector.ts
src/spec/command.spec.ts
src/spec/searcher/vulmon.spec.ts
src/spec/selector.spec.ts

feat: add Vulmon support

---

src/content.ts

I'm still looking for a better combination...

chore: change debounce to throttle

---

README.md
src/lib/scanner/urlscan.ts
src/spec/command.spec.ts

refactor: add /loading suffix

---

README.md
src/lib/command.ts
src/lib/searcher/blockcypher.ts
src/lib/searcher/index.ts
src/lib/searcher/searcher.ts
src/lib/searcher/searchers.ts
src/lib/selector.ts
src/spec/command.spec.ts
src/spec/searcher/blockcypher.spec.ts
src/spec/selector.spec.ts

- Add cryptocurrencies (BTC / XMR) search support
- Add BlockCypher search support

feat: add cryptocurrencies search support

---

src/lib/searcher/hybridanalysis.ts
src/spec/searcher/hybridanalysis.spec.ts
src/spec/selector.spec.ts

feat: add HA host/domain search support

---

src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/lib/searcher/zoomeye.ts
src/spec/searcher/zoomeye.spec.ts
src/spec/selector.spec.ts

feat: add ZoomEye support

---

README.md
src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/lib/searcher/spyonweb.ts
src/spec/searcher/spyonweb.spec.ts
src/spec/selector.spec.ts

feat: add SpyOnWeb support

---

src/lib/searcher/bgpview.ts
src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/spec/searcher/bgpview.spec.ts

feat: add BGPView support

---

src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/lib/searcher/threatminer.ts
src/spec/searcher/threatminer.spec.ts

feat: add ThreatMiner support

---

src/lib/searcher/urlscan.ts
src/spec/command.spec.ts
src/spec/searcher/urlscan.spec.ts

prefer semantics resouce location to searching

refactor: change urlscan.io searcher's behavior

---

README.md
src/lib/searcher/binaryedge.ts
src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/spec/searcher/binaryedge.spec.ts

feat: add BinaryEdge lookup

---

src/lib/searcher/shodan.ts
src/spec/backgroud.spec.ts
src/spec/searcher/shodan.spec.ts

Rewrite Shodan plugin for enabling more context oriented search

refactor: rewrite Shodan plugin

---

src/lib/command.ts
src/lib/searcher/censys.ts
src/spec/searcher/censys.spec.ts

Rewrite Censys plugin for enabling more context oriented search

refactor: rewrite Censys plugin

---

README.md
src/lib/searcher/archiveorg.ts
src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
src/spec/searcher/archiveorg.spec.ts

feat: add archive.org lookup

---

src/spec/backgroud.spec.ts
src/spec/command.spec.ts
src/spec/content.spec.ts
src/spec/options.spec.ts
src/spec/searcher/otx.spec.ts
src/spec/searcher/pubdb.spec.ts
src/spec/searcher/pulsedive.spec.ts
src/spec/searcher/riskiq.spec.ts
src/spec/searcher/securitytails.spec.ts
src/spec/searcher/talos.spec.ts
src/spec/searcher/threatcrowd.spec.ts
src/spec/searcher/threatminer.spec.ts
src/spec/searcher/urlscan.spec.ts
src/spec/searcher/viewdns.spec.ts
src/spec/searcher/virustotal.spec.ts
src/spec/searcher/xforce-exchange.spec.ts
src/spec/selector.spec.ts

Add a blank like to each section(context/describe/etc.)

refactor: add a blank line to each section

---

package-lock.json
package.json

Remove validator and update sinon & sinon-chrome

refactor: refactoring dependencies

---

dist/manifest.json

Add the add-on id for FireFox. (#81)

chore: add add-on id for FireFox

---

README.md

Add descriptions for the FireFox add-on. (#81)

docs: add desc for FireFox

---

README.md
src/lib/searcher/greynoise.ts
src/spec/searcher/greynoise.spec.ts

Catch up the latest change (GNQL support)

feat: revamp GreyNoise searcher

---

.travis.yml

update travis.yml to use node v12

chore: update travis.yml

---

src/lib/selector.ts

Remove xmr selection because it is never used

refactor: remove xmr selecton

---

src/lib/searcher/virustotal.ts
test/searcher/virustotal.spec.ts

Catch up to the latest VT's URL semantics

refactor: update VT searcher

---

src/lib/selector.ts

Change to use an internal slot to pick entries to scan/search

refactor: refactor getScannerEntries & getScannerEntries methods

---

README.md

docs: update README.md [skip travis]

---

README.md
src/lib/searcher/hybridanalysis.ts
test/searcher/hybridanalysis.spec.ts

Hybrid-Analysis - support other hashes

---

.eslintrc
package-lock.json
package.json

Revert "chore: add eslint-plugin-mocha"

---

src/lib/searcher/domainwatch.ts
test/searcher/domainwatch.spec.ts

Make enable to do more accurate reverse whois search on DomainWatch

update: revamp DomainWatch plugin

---

webpack.config.js

Change to show performance hits based on only .js files

chore: update Webpack performance config

---

src/lib/types.ts
src/manifest.json
src/options.ts
src/options/options.html
src/utility.ts

Revamp options page to make it more usable

feat: revamp Options page

---

src/lib/command.ts
src/lib/scanner/hybridanalysis.ts
src/lib/scanner/index.ts
src/lib/scanner/scanners.ts
src/lib/types.ts
src/options.ts
src/options/options.html
src/utility.ts
test/backgroud.spec.ts
test/command.spec.ts
test/options.spec.ts
test/scanner/hybridanalysis.spec.ts
test/scanner/selector.spec.ts

Add HybridAnalysis quick-scan integration

feat: add HybirdAnalysis quick scan

---

mocha.opts
package.json

refactor: add mocha.opts

---

src/options/options.html

Remove "Your" because it is obvious

refactor: update options UI

---

src/lib/searcher/censys.ts

Change to use a utilitliy method for extracting ASN from a string

refactor: refactor Censys plugin

---

src/lib/searcher/apklab.ts

Change to use `buildURL` and remove unused import

refactor: update Apklab

---

README.md
src/lib/searcher/anyrun.ts
src/lib/searcher/index.ts
src/lib/searcher/searchers.ts
test/searcher/anyrun.spec.ts

feat: add any.run

---

package-lock.json
package.json
src/lib/scanner/hybridanalysis.ts

Use camel-case in variable names

refactor: use camel-case

---

src/manifest.json

Update permissions to fix #404

refactor: update permissions

---

src/lib/searcher/onyphe.ts
test/searcher/onyphe.spec.ts

Catch up the latest Onyphe's URL schema

fix: update Onyphe plugin

---

package-lock.json
package.json

Use husky and lint-staged to keep basic quality of code

chore: use husky & lint-staged

---

package-lock.json
package.json
src/lib/selector.ts

Use extractXXX function of ioc-extractor instead of extractIOC

refactor: change the usage of ioc-extractor

---

package.json

refactor: rename build-zip command [skip ci]

---

README.md

docs: update readme [skip ci]

---

.eslintrc.js

Use Prettier along with ESLint

chore: update ESLint-Prettier configuration

---

src/lib/scanner/urlscan.ts

Change to show the detailed error message in urlscan

refactor: show error message in urlscan

---

package-lock.json
package.json
src/content.ts

Use @github/mini-throttle instead of throttle-debounce

refactor: use @github/mini-throttle

---

README.md

Add full-forms of OSINT & IoCs (#469)

docs: add full forms after abbreviations

---

src/manifest.json

quick attempt
testing needed
to be reviewed with travis testing

define content_security_policy - #464

---

package-lock.json
package.json

v0.79.0 [skip ci]

---

src/options.ts
src/options/options.html

Change to save options automatically by checking a "change" event

refactor: save options automatically

---

src/searcher/malwarebazaar.ts
src/types.ts
test/searcher/malwarebazaar.spec.ts

Support new search syntax (#553)

fix: update Malware Bazaar

---

README.md
src/searcher/censys.ts
test/searcher/censys.spec.ts

- Added more Censys queries
- Updated README.md
- Updated Censys test
Also I opened an issue on `ioc-extractor` for email address with dashes in it: https://github.com/ninoseki/ioc-extractor/issues/203

Update Censys Searcher

---

README.md
src/searcher/spyse.ts
test/searcher/spyse.spec.ts

Added CVE and email lookup using Spyse

Extend spyse support

---

src/searcher/spyse.ts
test/searcher/spyse.spec.ts

Hello. 
I made some fixes to Spyse integration.
Best regards.

fix: fixed spyse email search

---

src/background.ts
src/command/runner.ts

feat: show confirmation for the search all command

---

src/manifest.json
src/options/options.html
src/types.ts
src/utility.ts

Show favicon in the options page.

feat: show favicon in options

---

src/selector.ts

Reduce a number of slots to check

refactor: reduce number of slots to check

---

src/background.ts
src/content.ts
src/options.ts
src/options/options.html
src/types.ts
src/utility.ts
test/backgroud.spec.ts
test/content.spec.ts
test/options.spec.ts

Add "prefer href value" option to solve #653

feat: add "prefer href value" option

---

src/background.ts
test/backgroud.spec.ts

Improve the context menu management.
**Before**
- Remove previous context menus before creating new ones
**After**
- Remove previous context menus before creating new ones
- Remove created context menus after a context menu is clicked

refactor: improve context menu management

---

src/background.ts
src/content.ts
src/options.ts
src/options/options.html
src/selector.ts
src/types.ts
src/utility.ts
test/backgroud.spec.ts
test/options.spec.ts
test/selector.spec.ts

Add an option to enable/disable debug log (#687)

feat: add option to enable/disable debug log

---

README.md

Added a link to my repo. Thanks!

Adding my extension to "Alternatives or Similar Tools"

---

package-lock.json
package.json
src/options/index.vue

Remove Font Awesome to reduce the bundle size

chore: remove fontawesome [skip ci]

---

src/background/index.ts
src/command/runner.ts
src/types.ts

fix: fix search all issue (#712)

---

src/options/index.vue
src/types.ts

Add filter for searchers in the options page.

feat: filter for searchers

---

src/command/runner.ts

Fix hash type search all issue (#719)

fix: fix hash type search all issue

---

README.md
src/searcher/index.ts

Drop daed services
- DomainWatch: returns 500 error
- VulncodeDB: project abandoned

chore: drop dead services

---

README.md
src/searcher/index.ts
src/searcher/threatbook.ts
tests/searcher/threatbook.spec.ts

Support ThreatBook (threatbook.io) as a searcher

feat: support ThreatBook

---

src/options/index.vue
src/scanner/browserling.ts
src/scanner/hybridanalysis.ts
src/scanner/urlscan.ts
src/scanner/virustotal.ts
src/schemas.ts
src/selector.ts
src/types.ts
tests/selector.spec.ts

Make it possible to disable/enable scanners in the options.

feat: disable scanners (#713)

---

README.md
src/searcher/coalition.ts
src/searcher/index.ts
tests/searcher/coalition.spec.ts

Add Coalition searcher (CVE only)

feat: add Coalition searcher

---

package-lock.json
package.json
src/background/scan.ts
src/background/search.ts
src/command/runner.ts
src/scanner/browserling.ts
src/scanner/hybridanalysis.ts
src/scanner/urlscan.ts
src/scanner/virustotal.ts
src/schemas.ts
src/searcher/apklab.ts
src/searcher/inquest.ts
src/searcher/scumware.ts
src/searcher/vmray.ts
src/types.ts
tests/scanner/browserling.spec.ts
tests/scanner/hybridanalysis.spec.ts
tests/scanner/urlscan.spec.ts
tests/scanner/virustotal.spec.ts
tests/searcher/apklab.spec.ts
tests/searcher/inquest.spec.ts
tests/searcher/scumware.spec.ts
tests/searcher/vmray.spec.ts

refactor: use neverthrow

---

package-lock.json
package.json
src/storage.ts

fix: fix storage issue (#796)
